# Generated by Django 2.1.15 on 2021-07-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Algoritime_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='descripcion',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=30),
        ),
    ]
