# Generated by Django 2.1.15 on 2021-07-24 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Algoritime_app', '0002_auto_20210723_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(null=True, upload_to='blog'),
        ),
    ]
